pose:
  targets:
    start:
      

    WS01: 
      
   
    WS02: 
      

    WS03: 
      
    
    WS04:

    
    WS05:

    
    WS06:

    
    WS07:  

    WS08:

    WS09:

    WS10:

    WS11:

    WS12:

    WS13:

    WS14:

    SH01:

    SH02:

    RT01:

    GOAL:
      